FROM node:latest

# RUN npm install -g typescript
# RUN npm install -g @nestjs/cli
# WORKDIR /backend
# COPY . ./
WORKDIR /backend
# RUN npm install -g @nestjs/cli && npm install

EXPOSE 5000
EXPOSE 8002
EXPOSE 4000
EXPOSE 5050
CMD ["npm", "run", "start:dev"]
